#!/usr/bin/python3

import time
 
t = time.localtime(time.time())
localtime = time.asctime(t)
str = "Current Time:" + time.asctime(t)
 
print(str)a = 5
while a>=1:
    i=1
    while i<=a:
        print("*",end="")
        i+=1
    print()
    a-=1